hack4impact-utk/mission-of-hope

src/views/donationItemView/index.tsx
Problem: Page updates monthQuery if monthQuery is an empty string, causes a state update every time the component renders with an empty monthQuery, leading directly into another render. 
FIx:  useEffect hook that only runs once.
MoH - /donationItem` page error
[#11](https://github.com/hack4impact-utk/Maintenance-Team/issues/11)
<!-- For example:
https://jam.dev/c/5b536589-17d7-4717-a1d5-d408e1f00203
=> Fix page rerender with useEffect hook

src/views/AddDonationView/index.tsx
Add a property-checking condition to shrink the placeholder when there is an input value, so it does not overlap with the value generated by the button.
- https://github.com/hack4impact-utk/Maintenance-Team/issues/18
- Run the page and look
- Click GeneratingButton many times
- Manually input some value
- Resize the windows to ensure compatibility
=> Fix receipt text overlaps with placeholder text

src/views/donationIdView/index.tsx
- Remove the **Edit** toggle.
- Remove the **Cancel** toggle.
- Fields are always editable.
- Change the **Save** button's width to equal to the form's width.
- Change to function of **ViewDonation** button to go back, and it **keeps the filter in previous page** (Donation List).
- https://github.com/hack4impact-utk/Maintenance-Team/issues/35
=> MoH-/donation/[donationId]-Button-functionality

src/views/AddDonationView/index.tsx
Add donation form was adding donors and donation items when appropriate, but not donations. This was because the form data was being validated, but the `prevDonated` field was never set. This has been fixed.
https://github.com/hack4impact-utk/Maintenance-Team/issues/32
=> Fix add donation form not adding donations

src/app/api/mailMerge/route.ts, src/server/actions/mailMerge.ts, src/types/mailMerge.ts
- Replaced `/api/mailMerge` POST endpoint with PUT endpoint
- Replaced `createMailMerge()` server func with `upsertMailMerge()` in `/server/actions/mailMerge.ts`
Calls to the PUT endpoint will create a new document if there isn't one for the given mailType (receipt, monthly, yearly). If there is one, it will be updated. If there are multiple, the first is updated. Response is 201 if a new document is created, 200 if not.
https://github.com/hack4impact-utk/Maintenance-Team/issues/29
To verify that the feature works, send PUT requests with these bodies and check the database between each.
```
{
"type": "Monthly",
"subject": "Test Subject",
"body": "Test Body"
}
```
```
{
"type": "Monthly",
"subject": "Test Subject 2",
"body": "Test Body 2"
}
```
```
{
"type": "Yearly",
"subject": "Test …
```
=> Saveable email templates - prevent duplicate email templates

src/components/AccountMenu/index.tsx
Disable the button from accessing the scroll button.
- MoH - Profile picture button jumps on click
[#27](https://github.com/hack4impact-utk/Maintenance-Team/issues/27)
=> MoH - Profile picture button jumps on click #27

src/views/AddDonationView/index.tsx
Added clearing for the "Receipt" field when the "Submit Donation" button is pressed. Fixed by setting the receipt field to '' on a successful submission.
- hack4impact-utk/Maintenance-Team#46
I noticed this issue was rated as a 2 even though I think it's just a 1 line fix, so just wanted to make sure I wasn't missing anything. I tested to ensure that the Receipt field is cleared both when manually typed and when auto-generated, and then verified the data to make sure that the Receipt # being entered into the DB was correct.
=> Clear Receipt field on donation submission

src/components/AccountMenu/index.tsx
Add profile picture to account bar.
- MoH - display profile picture when logged in
[#39](https://github.com/hack4impact-utk/Maintenance-Team/issues/39)
=> MoH - display profile picture when logged in #39

src/app/api/mailMerge/route.ts, src/app/mailMerge/page.tsx, src/components/email-editor/index.tsx, src/views/MailMergeView/index.tsx
Email template editor is now populated with existing email templates. There is now a save button for each template which will save the contents of the email editor to the database by upserting with the current template type.
https://github.com/hack4impact-utk/Maintenance-Team/issues/28
Go to the page, type some stuff, press the save button, reload the page or check database and see that the stuff you wrote is now there.
=> 28 saveable email templactes frontend implementation

src/app/api/donations/route.ts, src/components/email-card/index.tsx, src/utils/string.ts
Sends email to donor on adding donation.
https://github.com/hack4impact-utk/Maintenance-Team/issues/30
There is a bug currently that prevents the Add Donation page from adding a new donor, so you'll have to add/edit an existing donor to use your email address. Once you've done that, add a donation from that donor and you'll get an email. Edit the Receipt email template to use `[FDONOR]`, `[LDONOR]`, and/or `[DATE]` to test the placeholder text replacement.
=>  MoH - Send email on donation #30 

src/components/donationItemForm/index.tsx
- Empty out the high/low evaluation value (ex. "High ($3.99)" -- the ($3.99) part of it) if the item or category is altered or removed.
- https://github.com/hack4impact-utk/Maintenance-Team/issues/45
- https://jam.dev/c/d93e8730-1e89-44b5-bf56-8dab7aaecc40
=> MoH - #45 - Clear high/low evaluation value from dropdown when clearing item/category

src/views/donationItemView/index.tsx, src/views/donorView/index.tsx, src/views/itemView/index.tsx
Updated the search filters on the Inventory, Donors, and Evaluations page using the same fix implemented [here](https://github.com/hack4impact-utk/mission-of-hope/pull/227). Reasonably standardized some of the code to make the pages more similar to /DonationView (Ex: using useSearch on /ItemView, updating 'id' field on /DonationItemView).
- hack4impact-utk/Maintenance-Team#51
if you don't want to hunt through the DB to find some _id values to test with, the 'edit' value still shows up in the export CSV's.
=> Removed 'edit' values from search

src/components/nav-bar/index.tsx
- Separate the side Navbar button into groups
- Make the button text smaller and reduce the spacing between them
- Have the buttons have zero margin
- Make the logo clickable, navigating to default page '`/`'.
- [Issue33](https://github.com/hack4impact-utk/Maintenance-Team/issues/33)
- [Jam Video](https://jam.dev/c/c3424d6d-7f4f-4cb3-b89c-bdeb300f7945)
=> MoH Reorganize Sidenav #33

src/app/api/users/route.ts, src/server/actions/settings.ts, src/server/actions/users.ts, src/server/models/settings.ts, src/types/settings.ts, src/types/users.ts
- Added Settings schema and zod types (currently just tracks allowed emails)
- Added server function to get settings
- Added server function and zod types to modify list of allowed users and which users are admins
- Added PUT endpoint to call these server functions
https://github.com/hack4impact-utk/Maintenance-Team/issues/43
=> Schema, server, and API support for modifying allowed users and admins

src/components/AccountMenu/index.tsx
- If user logged in, we display the settings and log-out option.
- If user did not logged in, we only display the log-in option.
- [Conditionally hide Login/Logout options](https://github.com/hack4impact-utk/Maintenance-Team/issues/60)
- Should we change the term `Settings` to `Account`?
=> MoH #60: Conditionally hide Login/Logout options

src/app/api/donations/[donationId]/route.ts, src/components/AccountMenu/index.tsx, src/views/donationIdView/index.tsx
- I made the field Receipt editable and updatable. However, the `Receipt` number could be duplicated if the same number already exists (but it is out of scope for this task).
- I also created a new API file to update a donation using its ID: ./src/app/api/donations/[donationId]/route.ts.
- [MoH - Allow editable receipts](https://github.com/hack4impact-utk/Maintenance-Team/issues/34)
- I did some edits to the **existing code** that is used to update the `Items` only:
- I renamed some variables and functions, and added some comments to clarify them.
- I have commented out the irrelevant code to turn off warnings because it is out-of-scope for this task.
=> MoH #34: Allow editable receipts

src/components/donation-form/AutofillDonorEmail.tsx, src/components/generateReceiptButton/index.tsx, src/views/AddDonationView/index.tsx
- Disable all the fields and buttons while submitting on /donation/add page.
- Show a loading circle instead of "Submit Donation" text while submitting on /donation/add page.
- [MoH#73](https://github.com/hack4impact-utk/Maintenance-Team/issues/73)
- I added the `disable` property for the **./src/components/donation-form/AutofillDonorEmail.tsx** so we can reuse it for other pages.
=> MoH #73: Disable the entire page and show loading circle while submitting

package-lock.json, package.json, src/app/api/admins/[userId]/remove/route.ts, src/app/settings/page.tsx, src/app/settings/users/page.tsx, src/components/AccountMenu/index.tsx, src/components/LoadingButton/index.tsx, src/components/nav-bar/index.tsx, src/server/actions/users.ts, src/views/settingsView/AdminAutocomplete/index.tsx, src/views/settingsView/UserList/index.tsx, src/views/settingsView/index.tsx
- Replaced old `/settings` page with dashboard for adding/removing admins and allowed emails. (EDIT: Also moved to `/settings/users`)
- Added server function and API route for removing an admin
- Added loading button component
https://github.com/hack4impact-utk/Maintenance-Team/issues/41
(also went ahead and did backend)
Just go to `/settings` and add and remove stuff, it should work.
NOTE: Most of the current dummy user data in the database is wrong, so there'll be a bunch of empty lines in the add admin dropdown from those. The users with `name`, `email`, `image`, and `isAdmin` fields will show up correctly.
=> User Dashboard

src/views/AddDonationView/index.tsx
Submitting the Add Donation form no longer removes the `_id` field from the donor form data, which previously prevented adding a new donor through the form after submitting it the first time without reloading the page.
I'm pretty sure this fixed the issue, as I wasn't able to recreate it after the fix, but the add donation form code is a complete mess and there could still be some way to trigger the issue I didn't see.
https://github.com/hack4impact-utk/Maintenance-Team/issues/52
Fill out and submit the Add Donation form. Then fill it out again without reloading, with the donor section containing info for a new donor. Submit it again, and it should add the new donor.
=> Fix adding new donor when adding donation

src/views/AddDonationView/index.tsx, src/views/donationItemView/index.tsx, src/views/donationView/index.tsx, src/views/donorView/index.tsx, src/views/itemView/index.tsx
Makes it so when you click an option on a table column selector, it will not minimize. It is multi select, so having to reopen it multiple times to select all the options you want was quite frustrating
[#67](https://github.com/hack4impact-utk/Maintenance-Team/issues/67)
=> Prevent columns dropdown from closing on click on tables

src/app/item/[itemId]/page.tsx, src/views/itemIdView/index.tsx
Adds functionality to the category dropdown on the item evaluation edit page, so it behaves the same as it does on the item evaluation add page. The functionality was there, it just wasn't being passed any data
Closes [#65](https://github.com/hack4impact-utk/Maintenance-Team/issues/65)
=> `/item/{itemId}` Category Dropdown

src/server/models/audit.ts, src/types/audit.ts
Added zod and mongoose types for audits.
Updated audit schema diagram (`actor` -> `user`, added `doc`)
https://github.com/hack4impact-utk/Maintenance-Team/issues/91
Mongoose provides `refType:` as a hip and cool way to populate fields with dynamic types, such as `doc`. Does zod provide any sort of dynamic typing that I could use to include an optional populated doc in `zAuditResponse`? I wasn't able to find anything, but I didn't dig for that long.
Also, is there any way to test this code before we add server actions?
=> MoH #91 Create audit server/typescript types
