hack4impact-utk/mission-of-hope

- src/app/api/donations/route.ts
- src/server/models/donors.ts
- src/server/models/items.ts
- src/server/models/users.ts
- src/types/persons.ts
Fixed some issue with the schema and the types. This is the wrong branch but I didn't want to commit it directly to main
> Fixed the item schema and persons naming

- src/app/api/users/route.ts
- src/server/actions/users.ts
> #27 & #29 - Implemented creating a new user

- scripts/createTestData.script
- src/server/models/donationItem.ts
- test/EXdonation.json
- test/EXdonationitem.json
- test/EXdonor.json
- test/EXitem.json
- test/EXuser.json
Just adding a script and fixing a naming issue
> Example data mongodb

- src/app/api/donationItem/[donationItemId]/route.tsx
- src/server/actions/donationItem.ts
- src/server/actions/donors.ts
- src/server/models/donationItem.ts
- src/server/models/donors.ts
- src/server/models/items.ts
- src/server/models/users.ts
> Added server and api routing for getting donation item by id

- src/app/donation/page.tsx
- src/app/donation/styles.module.css
Implemented UI to add donations. which includes a form.
44
> Implement UI to add donations

- src/app/api/users/[userId]/route.ts
- src/server/actions/users.ts
Added server and API routing for getting user by id
**FOR TESTING**: This API call `localhost:3000/api/users/65ce84429aca7f652bd1fd30` will return `Davis Michael` user.
62
> Added server and api routing for getting user by id

- src/app/api/donationItem/route.tsx
- src/server/actions/donationItem.ts
- src/server/models/donationItem.ts
- src/types/donation.ts
> add post for donation item

- src/app/api/donations/route.ts
- src/app/api/users/route.ts
- src/server/actions/donations.ts
- src/types/donation.ts
I fixed the donation api to match up with the documentation
- #70
> Fixed some issues with the donation model

- src/app/api/items/route.ts
- src/server/actions/items.ts
Updated changes to create items
1. import from Next error
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have assigned reviewers to this PR
> MOH-35-API routing for item creation

- src/app/page.tsx
> created landing page and styled

- src/app/donors/page.tsx
This is for issue 51 and 46
Added function to grab all the donor data. Used Mui cards to display the data
I'm calling the function that the API uses to get all of the data because I'm not sure how to actually call our API. How could I alternatively call the API?
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have assigned reviewers to this PR
> added function do get and display donors

- src/app/user/page.tsx
Uses a card using mui that is centered and stacked. Tested using example users.
#47
> View Users Page

- .github/ISSUE_TEMPLATE/story.md
Just adding a story template to make it easy to make new issues
> Update issue templates

- scripts/createTestData.script
- src/app/api/donations/route.ts
- src/server/actions/donations.ts
- src/server/models/donationItem.ts
- src/server/models/donors.ts
- src/types/donation.ts
- src/types/persons.ts
- test/EXdonor.json
I have updated the donor and donation schemas.
- Added `.populate(["user", "donor"])` to the get all donations function to help display the donations
- Added city, state, and zip to the donor
#88 
#97 
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code
> 88 fix donor schema and donation schemas

- src/app/item/add/page.tsx
Connected ```src/app/item/add/``` to the server with a post request
#76 Connect add Item to back end 
I did not use as many dependencies as the example used like Snackbar. not sure if they're needed.
I also only wrote a console log after it was submitted and nothing visual for the user.
> Alan kha/connect add item to back end

- package-lock.json
- package.json
- src/app/donors/page.tsx
- src/views/donorView/index.tsx
Refactored view donors page to use Data table to display data and follows view convention now.
Here is how it looks now:
#108
#110 
#94
> Refactored view donors page 

- src/app/donationItem/page.tsx
- src/views/donationItemView/index.tsx
Converted the donation item page to view convention
#109
> Converted donation item page to view

- src/views/AddDonationView/index.tsx
Only allows for users to enter prices and will throw an error if you enter a negative number
#118
> 118 allow for users to only enter prices on add donation page item price

- src/hooks/useValidation.ts
- src/types/forms/donation.ts
- src/types/forms/item.ts
- src/views/AddDonationView/index.tsx
Added some zod types to use for form validation
#150
> Stop empty fields with zod

- package-lock.json
- package.json
- pnpm-lock.yaml
- src/app/api/mailMerge/route.ts
- src/app/layout.tsx
- src/app/mailMerge/page.tsx
- src/components/email-card/index.tsx
- src/components/email-editor/index.tsx
- src/components/tab-panel/index.tsx
- src/components/tool-bar/index.js
- src/components/tool-bar/style.css
- src/server/actions/donations.ts
- src/server/actions/mailMerge.ts
- src/server/models/mailMerge.ts
- src/types/donation.ts
- src/types/mailMerge.ts
- src/utils/moh-theme.ts
- src/views/MailMergeView/index.tsx
Created a react-quill form to create an email. Added string parsing to allow for mail merging (ex. [FDONOR] -> John)
#149
> 149 add a mail merge page for receipts, Monthly, yearly

- src/views/donorIdView/index.tsx
- src/views/donorView/index.tsx
Created a button on the donor view page that links to the edit donor page. Also improved the look of the table to fit the button. Also added a button that goes back to the view donor page.
> 141 Created an edit button to link to donor edit page

- src/views/AddDonationView/index.tsx
Converted New/Used and High/Low to dropdown, and disabled the appropriate fields
#99 Limit user selection of item evaluation
The disabled property is kind of hard to tell that it's disabled without clicking on it. may need to add some styling to make it more apparent.
> 99 limit user selection of item evaluation

- src/app/layout.tsx
- src/components/Providers.tsx
- src/hooks/useSnackbar/SnackbarContext.tsx
- src/hooks/useSnackbar/index.ts
- src/views/AddDonationView/index.tsx
- src/views/addItemView/index.tsx
Added a global snackbar that can be used in any component. Code was borrowed from another Hack4Impact project.
#143 
- [ X] New feature (non-breaking change which adds functionality)
> 143 add a small popup at the top of screen on success after add item page

- src/app/page.tsx
> 52 home page

- src/types/forms/donation.ts
- src/views/AddDonationView/index.tsx
Add validation to add the donation form, remove the overlap of donation data and donor data form types
#121
> Add validation to add donation form

- src/app/settings/page.tsx
- src/components/AccountMenu/index.tsx
- src/components/top-bar/index.tsx
- src/views/settingsView/index.tsx
- Added AccountMenu with login, settings, and logout options. 
- Added frontend for settings page
#135 
#136
> Added AccountMenu with login, settings, and logout options. Added frontend for settings page

- src/app/donors/page.tsx
- src/views/donorView/index.tsx
- tsconfig.json
Add sorting dropdown to view donors table
I had to modify `tsconfig.ts` because this line `[...Array(12).keys()]` was giving some ts error.
#106
> Add sorting dropdown to view donors table

- src/app/item/page.tsx
- src/components/nav-bar/index.tsx
- src/views/itemView/index.tsx
Used the donor table to create the item table and add an edit button that links to the edit page for that item.
#170
> Edit button added to the view items page

- src/views/AddDonationView/index.tsx
- src/views/addItemView/index.tsx
- src/views/donorIdView/index.tsx
- src/views/itemIdView/index.tsx
> Added snackbar popups for all forms currentlly implemented

- src/app/donationItem/add/page.tsx
- src/views/donationItemView/index.tsx
- src/views/donorView/index.tsx
I also fixed some issues with the donor page
#175
> Fixed the look of the inventory page

- src/app/donation/page.tsx
- src/components/donation-form/AutofillCategory.tsx
- src/components/donation-form/AutofillItem.tsx
- src/components/donationItemForm/index.tsx
- src/types/forms/donation.ts
- src/types/forms/donationItem.ts
- src/views/AddDonationView/index.tsx
> 101 allow for the user to add more than one donation item

- src/components/donation-form/AutofillCategory.tsx
- src/components/donation-form/AutofillItem.tsx
- src/components/donationItemForm/index.tsx
- src/types/forms/donationItem.ts
- src/views/AddDonationView/index.tsx
This should create a new item if no item is selected
#93
> Create new item on donation item page

- src/views/AddDonationView/index.tsx
I think there is an issue with the snackbar errors but it has not been tested
#95
> donation items created when adding a donation

- src/app/donationItem/page.tsx
- src/views/donationItemView/index.tsx
> Added the ability to sort donation items by month

- src/server/actions/donations.ts
- src/views/donationView/index.tsx
> 105 add the ability to sort the donation history page by month

- src/components/donationItemForm/index.tsx
- src/types/forms/donationItem.ts
- src/views/AddDonationView/index.tsx
> Added barcode to donation item

- src/server/actions/email.ts
Email func now uses html formatting
> fixed email html

- src/components/donationItemForm/index.tsx
- src/components/donorForm/index.tsx
- src/views/AddDonationView/index.tsx
Rearranged the form on the "Add Donation" page to be more visually appealing and easier to navigate. Form fields are only split along 1/2 or 1/3 intervals, and similar splits are placed near each other (except in first and second line where this wouldn't make much sense). Tried to make the form look better on smaller screens as well.
- hack4impact-utk/Maintenance-Team#14
- Run the page and look
- Make window small to see if small screen sizing is acceptable
> Fix "Add Donation" view

- src/views/addItemView/index.tsx
Clears form on submit 
Proper controlled form state handling
MoH - Add Item clear form on submission
[#21](https://github.com/hack4impact-utk/Maintenance-Team/issues/21)
> 21 moh   add item clear form on submission

- src/views/addItemView/index.tsx
- Show a loading wheel while processing the submission.
- Use the **CircularProgress** from **@mui/material** so no need to install new package
- https://github.com/hack4impact-utk/Maintenance-Team/issues/24
- I have tested it with sleep(2 second) to ensure it actually works because it happens rapidly.
- https://jam.dev/c/54a44652-fee4-4557-b862-1e657c223e04
> MoH-24-Add Item-Show a loading wheel on submit

- src/views/addItemView/index.tsx
- Follow-up with: https://github.com/hack4impact-utk/mission-of-hope/pull/214
- Disable the form and the button while it's loading.
- https://github.com/hack4impact-utk/Maintenance-Team/issues/24
> MoH-24-Follow-up-Add item-Disable the form and the button while loading

- src/components/donation-form/AutofillCategory.tsx
- src/components/donationItemForm/index.tsx
> Autofilled the Category

- src/views/donorView/index.tsx
I fixed the rerender in the /donors/index.tsx by using a useEffect wrapped around the if(monthquery == ' ') to stop it from infinitely rerendering.
Error Fix?
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [ X] I have assigned reviewers to this PR
> fixed rerender issue on donor link

- src/components/top-bar/index.tsx
We agreed (mostly) as a team and said we would make the addbar static at the top of the screen. Thus the only thing I did was change the position value from 'sticky' to 'static'
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have assigned reviewers to this PR
> MoH - Make header app bar opaque #13

- src/app/item/add/page.tsx
- src/components/itemForm/index.tsx
- src/server/actions/items.ts
- src/views/addItemView/index.tsx
- src/views/itemIdView/index.tsx
Added an autofill box for the Category field in the page for adding new items. This was done by adding a function to get a list of all unique categories from the DB and then passing it down to the itemForm component. We opted to use a conditionally rendered "This will add a new item" field instead of adding an "Add ____" to the filter options.
- hack4impact-utk/Maintenance-Team#12
- Let me know if I didn't resolve the merge conflict correctly (commit 2/2). Thanks!
> Added category autofill for adding new items

- src/views/donationView/index.tsx
Removed the "Quantity" column and added "Receipt Number" column to the Donations page. Tested that the search functionality works as intended with receipt numbers.
- hack4impact-utk/Maintenance-Team#37
> Added "Receipt Number" column to Donations table

- src/app/donors/page.tsx
- src/views/donorView/index.tsx
Simply removed all code related to the Month selector and associated month sorting in the search bar. The search bar can no longer filter by month, though it's hard to test (see associated msg in PR channel).
- hack4impact-utk/Maintenance-Team#47
> MoH - Removed "month" selector from Donors page #47

- src/app/donation/page.tsx
- src/hooks/useMonth.ts
- src/hooks/useYear.ts
- src/server/actions/donations.ts
- src/server/models/donationItem.ts
- src/views/donationView/index.tsx
Referenced the formatting for the existing month selector to add the year selector. I Changed the filtering logic to account for both parameters, and set the queries to correctly initialize both fields on page load.
- hack4impact-utk/Maintenance-Team#38
> Added year selector to Donations page

- src/components/AccountMenu/index.tsx
Adds log out functionality
- MoH - Add Logout functionality
[#40](https://github.com/hack4impact-utk/Maintenance-Team/issues/40)
> MoH - Add Logout functionality #40

- src/views/donationItemView/index.tsx
- src/views/donationView/index.tsx
- src/views/donorView/index.tsx
- src/views/itemView/index.tsx
The current export and column button is implemented by simply calling GridToolbar. It's a function the mui library that provides  with the basic functionalities export and column. I tried to see if the function was customizable. I didn't have too much luck, so I have shifted to just creating our own export csv function/button. 
MoH - Fix table exports
[#48](https://github.com/hack4impact-utk/Maintenance-Team/issues/48)
> MoH - Fix table exports #48

- src/components/donation-form/AutofillDonorEmail.tsx
- src/components/donorForm/index.tsx
- src/views/AddDonationView/index.tsx
clears out the autocompleted donor information when email box is cleared
[#31](https://github.com/hack4impact-utk/Maintenance-Team/issues/31)
> clear form when email is cleared

- src/views/donationView/index.tsx
- I changed the default selection from Current-Month to All-Month on the Donation page.
- [MoH#82](https://github.com/hack4impact-utk/Maintenance-Team/issues/82)
> MoH #82: Default All-Month selection on Donation page

- package-lock.json
- package.json
- src/components/email-editor/index.tsx
- src/components/tool-bar/index.tsx
- src/components/tool-bar/style.css
- The error was due to a deprecated feature that will not receive support after March 25, 2025 ([Detail Link](https://chromestatus.com/feature/5083947249172480)).
- The deprecation comes from **`react-quill`** that is only used by the page **/mailMerge**.
- I found a solution: Install a new actively-updated package named **`react-quill-new`** to replace **`react-quill`** ([Here is the discussion I found on GitHub](https://github.com/zenoamaro/react-quill/issues/970)).
- Due to the replacement, I also had to remove some unnecessary files and the old package.
- I have tested it after the replacement, and it works fine.
- Make sure you run the command **`npm install`** before testing.
- [MoH#62](https://github.com/hack4impact-utk/Maintenance-Team/issues/62)
> MoH #62:  Console error on page /mailMerge

- src/views/itemView/index.tsx
- Remove 'id' from the table, drop-down options, and exported CSV file.
- [MoH#81](https://github.com/hack4impact-utk/Maintenance-Team/issues/81)
> MoH #81: Remove 'id' from table, drop-down options, and exported csv file

- src/views/donorView/index.tsx
- I fixed the console error on /donors page.
- [MoH#68](https://github.com/hack4impact-utk/Maintenance-Team/issues/68)
> MoH #68: Console error on /donors page

- src/views/signInView/index.tsx
- Fix the Sign-in page: image does not overlap the Navbar. Also change the tag `<img>` to `<Image>` from `next/image` to improve efficiency.
- Fix the Sign-in page: everything is clickable now.
- [Issue#61](https://github.com/hack4impact-utk/Maintenance-Team/issues/61)
> MoH #61: Fix signin page display

- src/utils/string.ts
- Fixed the crash on Mailmerge/Preview.
- [MoH#63](https://github.com/hack4impact-utk/Maintenance-Team/issues/63)
> MoH #63: Crash on Mailmerge/Preview

- src/views/AddDonationView/index.tsx
Easy fix!
[#71](https://github.com/hack4impact-utk/Maintenance-Team/issues/71)
> `/donation/add` console errors

- src/components/AccountMenu/index.tsx
- src/views/donationView/index.tsx
Quick ol fix to the console errors on the donation page
[#69](https://github.com/hack4impact-utk/Maintenance-Team/issues/69)
> Donation page console errors

- src/views/donationView/index.tsx
Added one line that puts the receipt number in the csv file
[MoH #83](https://github.com/hack4impact-utk/Maintenance-Team/issues/83)
> Added receipt number in its own column to csv export

- src/components/nav-bar/index.tsx
- Make the Navbar expansion persistent while navigating to other pages.
- [Issue #80](https://github.com/hack4impact-utk/Maintenance-Team/issues/80)
- For pages that are not included in the Navbar, it automatically collapses.
> MoH #80: Persistent navbar expansion

- src/views/AddDonationView/index.tsx
- Disable auto-fill on Receipt field
- [Issue #70](https://github.com/hack4impact-utk/Maintenance-Team/issues/70)
> MoH #70: Remove auto-fill for Receipt field

- src/views/donationItemView/index.tsx
- Remove 'Edit' feature from Inventory page.
- [Issue 78](https://github.com/hack4impact-utk/Maintenance-Team/issues/78)
> MoH #78: Remove Edit feature from Inventory page
